name: Run E2E & contract tests

on: 
  push:
    branches:
      - main

env:
  version: "1.2.3"
  application_name: "conf_talks_server"
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/conf-talks-server
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  e2e:
    name: "e2e tests"
    runs-on: ubuntu-latest
    needs: push_to_registry

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get ./...
      - name: Run e2e on main
        run: E2E=true go test ./e2e -v

  publish-pact-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pactflow/actions/publish-pact-files@v1.0.1
        env:
          pactfiles: contract_test/pacts

  contract:
    name: "run contract tests"
    runs-on: ubuntu-latest
    needs: [push_to_registry, publish-pact-files]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get ./...
      - name: Install Pact
        run: curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-ruby-standalone/master/install.sh | PACT_CLI_VERSION=v2.0.2 bash
      - name: Run contract tests on main 
        run: CONTRACT=true REMOTE=true go test ./contract_test -v