name: Run unit & integration tests on main
on: 
  push:
    branches:
      - main

jobs:
  integration:
    name: "run integration tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get ./...
      - name: Run all tests on main
        run: INTEGRATION=true go test ./... -v